In [1]:
import pandas as pd
from google.colab import files
import io

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import time
import random
import os
from math import *

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error as MAPE
from sklearn.metrics import mean_squared_error as MSE
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error as MAE

In [3]:
uploaded = files.upload()

Saving test_set.csv to test_set.csv

In [4]:
df_test = pd.read_csv(io.BytesIO(uploaded['test_set.csv']))

In [5]:
uploaded = files.upload()

Saving df_complete.csv to df_complete.csv

In [6]:
df1 = pd.read_csv(io.BytesIO(uploaded['df_complete.csv']))

In [ ]:
'''
df1 = pd.read_csv(io.BytesIO(uploaded['pricing_requests_20req_eachdate.csv']))
df2 = pd.read_csv(io.BytesIO(uploaded['pricing_requests_34reqforlistdates.csv']))
df3 = pd.read_csv(io.BytesIO(uploaded['pricing_requests_92req_sofia.csv']))
df4 = pd.read_csv(io.BytesIO(uploaded['pricing_requests_92req_valletta.csv']))
df5 = pd.read_csv(io.BytesIO(uploaded['pricing_requests_100req.csv']))
df6 = pd.read_csv(io.BytesIO(uploaded['pricing_requests_500randomreq.csv']))
df7 = pd.read_csv(io.BytesIO(uploaded['pricing_requests_500randomreq_date1.csv']))
df8 = pd.read_csv(io.BytesIO(uploaded['pricing_requests_cities_3000_3100req.csv']))
'''

In [ ]:
#df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8])

In [7]:
df1

,Unnamed: 0,hotel_id,price,stock,city,date,language,mobile,avatar_id
0,0,151,241,70,rome,22,latvian,0,90844
1,1,38,100,15,rome,22,latvian,0,90844
2,2,129,106,22,rome,22,latvian,0,90844
3,3,344,72,19,rome,22,latvian,0,90844
4,4,180,75,10,rome,22,latvian,0,90844
...,...,...,...,...,...,...,...,...,...
275500,50319,994,197,1,copenhagen,1,czech,0,90843
275501,50320,58,328,1,copenhagen,1,czech,0,90843
275502,50321,445,91,0,copenhagen,1,czech,0,90843
275503,50322,53,96,0,copenhagen,1,czech,0,90843
275504,50323,664,482,1,copenhagen,1,czech,0,90843

In [ ]:
y = df1['price']
X = df1.copy()
del X['price']

In [8]:
cities = ['amsterdam', 'copenhagen', 'madrid', 'paris', 'rome', 'sofia', 'valletta', 'vienna', 'vilnius']

#calculate the mean prices for each city
mean_cities = []
for city in cities:
  #isolate the city
  rslt_df = df1[df1['city'] == city]
  #rslt_df['city'] =np.mean(rslt_df['price'])
  mean_cities.append(np.mean(rslt_df['price']))

city_mean = dict(zip(cities,mean_cities))

In [9]:
city_mean['paris']

188.13345242686913

In [36]:
def transform_original(df_original):
  new_df = df_original.copy()

  dfs = []
  for city in cities:
    rslt_df = new_df[new_df['city'] == city]
    rslt_df['city'] = city_mean[city]
    dfs.append(rslt_df)
  new_df = pd.concat(dfs)
  new_df = new_df.sort_index(ascending=True)
  y = new_df['price']
  X = new_df.copy()
  X =X[['hotel_id',	'stock',	'city',	'date', 'mobile']]
  
  X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

  return X_train, X_val, y_train, y_val

In [37]:
X_train, X_val, y_train, y_val = transform_original(df1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [13]:
X_train

        hotel_id  stock        city  date
136112        31     85  136.739065    39
81946        180      1  146.036088    14
172170       233     40  136.739065    28
145195       777    132  164.459531    43
262097       769      0  146.036088     1
...          ...    ...         ...   ...
119879       167     22  155.604270    31
259178       844      1  193.761292     1
131932       612    127  188.133452    37
146867       849    138  193.761292    44
121958       468     26  136.739065    32

[220404 rows x 4 columns]

In [22]:
df_test

,index,order_requests,city,date,language,mobile,avatar_id,hotel_id,stock
0,0,1,vilnius,21,romanian,0,1,161,46
1,1,1,vilnius,21,romanian,0,1,187,32
2,2,1,vilnius,21,romanian,0,1,279,12
3,3,1,vilnius,21,romanian,0,1,395,10
4,4,1,vilnius,21,romanian,0,1,488,42
...,...,...,...,...,...,...,...,...,...
6639,6639,843,rome,5,irish,0,794,987,1
6640,6640,844,vienna,1,irish,1,794,26,1
6641,6641,844,vienna,1,irish,1,794,263,0
6642,6642,844,vienna,1,irish,1,794,456,0
6643,6643,844,vienna,1,irish,1,794,699,0

In [24]:
X_train

        hotel_id  stock        city  date
136112        31     85  136.739065    39
81946        180      1  146.036088    14
172170       233     40  136.739065    28
145195       777    132  164.459531    43
262097       769      0  146.036088     1
...          ...    ...         ...   ...
119879       167     22  155.604270    31
259178       844      1  193.761292     1
131932       612    127  188.133452    37
146867       849    138  193.761292    44
121958       468     26  136.739065    32

[220404 rows x 4 columns]

In [30]:
y_train

136112     84
81946      74
172170    132
145195    148
262097     82
         ...
119879     82
259178    509
131932    192
146867    148
121958     67
Name: price, Length: 220404, dtype: int64

In [38]:
X_test

      hotel_id  stock        city  date  mobile
0          161     46  110.454557    21       0
1          187     32  110.454557    21       0
2          279     12  110.454557    21       0
3          395     10  110.454557    21       0
4          488     42  110.454557    21       0
...        ...    ...         ...   ...     ...
6639       987      1  146.036088     5       0
6640        26      1  155.604270     1       1
6641       263      0  155.604270     1       1
6642       456      0  155.604270     1       1
6643       699      0  155.604270     1       1

[6644 rows x 5 columns]

In [39]:
def transform_test(df_test):
  X_test = df_test.copy()
  X_test = X_test[['hotel_id', 'stock', 'city',	'date', 'mobile']]
  dfs = []
  for city in cities:
    rslt_df = X_test[X_test['city'] == city]
    rslt_df['city'] = city_mean[city]
    dfs.append(rslt_df)
  new_df = pd.concat(dfs)
  new_df = new_df.sort_index(ascending=True)
  return new_df

In [40]:
X_test = transform_test(df_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [41]:
X_test

      hotel_id  stock        city  date  mobile
0          161     46  110.454557    21       0
1          187     32  110.454557    21       0
2          279     12  110.454557    21       0
3          395     10  110.454557    21       0
4          488     42  110.454557    21       0
...        ...    ...         ...   ...     ...
6639       987      1  146.036088     5       0
6640        26      1  155.604270     1       1
6641       263      0  155.604270     1       1
6642       456      0  155.604270     1       1
6643       699      0  155.604270     1       1

[6644 rows x 5 columns]

In [42]:
X_test

      hotel_id  stock        city  date  mobile
0          161     46  110.454557    21       0
1          187     32  110.454557    21       0
2          279     12  110.454557    21       0
3          395     10  110.454557    21       0
4          488     42  110.454557    21       0
...        ...    ...         ...   ...     ...
6639       987      1  146.036088     5       0
6640        26      1  155.604270     1       1
6641       263      0  155.604270     1       1
6642       456      0  155.604270     1       1
6643       699      0  155.604270     1       1

[6644 rows x 5 columns]

In [43]:
from xgboost import XGBRegressor
regressor = XGBRegressor(learning_rate=0.01,  
                      colsample_bytree = 1,
                      subsample = 1,
                      n_estimators=300, 
                      reg_alpha = 0.3,
                      max_depth=10, 
                      gamma=0)
regressor.fit(X_train,y_train)

[15:39:36] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(learning_rate=0.01, max_depth=10, n_estimators=300, reg_alpha=0.3)

In [20]:
Y_pred_test = regressor.predict(X_test)

In [18]:
c=20
def save_prediction(Y_pred_test, c):
  Y_pred_test = regressor.predict(X_test)
  Y_pred_test = pd.DataFrame(Y_pred_test)
  Y_pred_test.rename(columns={'0':'price'})
  name = 'Y_pred_test_'+str(c)+'.csv'
  Y_pred_test.to_csv(name)

In [21]:
save_prediction(Y_pred_test, c)

In [ ]:
#Score=50

In [ ]:
uploaded = files.upload()
df9 = pd.read_csv(io.BytesIO(uploaded['455_pricing_requests_date22_unzipped.csv']))

Saving 455_pricing_requests_date22_unzipped.csv to 455_pricing_requests_date22_unzipped.csv

In [ ]:
df_complete = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9])

In [ ]:
cities = ['amsterdam', 'copenhagen', 'madrid', 'paris', 'rome', 'sofia', 'valletta', 'vienna', 'vilnius']

#calculate the mean prices for each city
mean_cities = []
for city in cities:
  #isolate the city
  rslt_df = df_complete[df_complete['city'] == city]
  #rslt_df['city'] =np.mean(rslt_df['price'])
  mean_cities.append(np.mean(rslt_df['price']))

city_mean = dict(zip(cities,mean_cities))

In [ ]:
X_train, X_val, y_train, y_val = transform_original(df_complete)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [ ]:
from xgboost import XGBRegressor
regressor = XGBRegressor(learning_rate=0.01,  
                      colsample_bytree = 1,
                      subsample = 1,
                      n_estimators=1000, 
                      reg_alpha = 0.3,
                      max_depth=10, 
                      gamma=0)
regressor.fit(X_train,y_train)

[14:54:45] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

KeyboardInterrupt: ignored

In [ ]:
Y_pred_test = regressor.predcit(X_test)

In [ ]:
c=17
save_prediction(Y_pred_test, c)